export default {
    EMAIL_EXIST: 'EMAIL_EXIST',
    PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
    EMAIL_NOT_SET: 'EMAIL_NOT_SET',
    INTERNAL: 'INTERNAL',
    CATEGORY_NAME_NOT_SET: 'CATEGORY_NAME_NOT_SET',
    PRODUCER_NAME_NOT_SET: 'PRODUCER_NAME_NOT_SET',
    REVIEW_NAME_NOT_SET: 'REVIEW_NAME_NOT_SET',
    PRODUCT_NAME_NOT_SET: 'PRODUCT_NAME_NOT_SET',
    CATEGORY_EXIST: 'CATEGORY_EXIST',
    WRONG_PASSWORD: 'WRONG_PASSWORD'
}
